user_id: your-spotify-account-id
client_id: your-spotify-app-client-id
client_secret: your-spotify-app-client-secret
redirect_uri: your-spotify-app-redirect-uri
generator:
# region_code: playlist_id
  global: your-global-top-200-playlist-id
  us: your-us-top-200-playlist-id
