user_id: your-spotify-account-id
client_id: your-spotify-app-client-id
client_secret: your-spotify-app-client-secret
redirect_uri: your-spotify-app-redirect-uri
generator:
# region: playlist_id || chart_url
  global: your-global-top-200-playlist-id || https://spotifycharts.com/regional/global/daily/latest/download
  us: your-us-top-200-playlist-id || https://spotifycharts.com/regional/us/daily/latest/download
