name: scheduled spotify top 200 playlists update

on:
  push:
    branches:
      - master
      - test-actions
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0,6,12,18 * * *'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set environment variables with secrets and update playlists
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          AUTH_CACHE: ${{ secrets.AUTH_CACHE }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: python generate_top_200_playlist.py

      - name: Delete local authorization cache file
        run: rm -f .cache
